from Colorized import *


# Bold
PrintWith(Colorize(BOLD, BLACK), "Hello world!")
PrintWith(Colorize(BOLD, RED), "Hello world!")
PrintWith(Colorize(BOLD, GREEN), "Hello world!")
PrintWith(Colorize(BOLD, BLUE), "Hello world!")
PrintWith(Colorize(BOLD, YELLOW), "Hello world!")
PrintWith(Colorize(BOLD, BLUE), "Hello world!")
PrintWith(Colorize(BOLD, MAGENTA), "Hello world!")
PrintWith(Colorize(BOLD, CYAN), "Hello world!")
PrintWith(Colorize(BOLD, WHITE), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_BLACK), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_RED), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_GREEN), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_BLUE), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_YELLOW), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_BLUE), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_MAGENTA), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_CYAN), "Hello world!")
PrintWith(Colorize(BOLD, LIGHT_WHITE), "Hello world!")

# Default.
PrintWith(Colorize(SDEFAULT, BLACK), "Hello world!")
PrintWith(Colorize(SDEFAULT, RED), "Hello world!")
PrintWith(Colorize(SDEFAULT, GREEN), "Hello world!")
PrintWith(Colorize(SDEFAULT, BLUE), "Hello world!")
PrintWith(Colorize(SDEFAULT, YELLOW), "Hello world!")
PrintWith(Colorize(SDEFAULT, BLUE), "Hello world!")
PrintWith(Colorize(SDEFAULT, MAGENTA), "Hello world!")
PrintWith(Colorize(SDEFAULT, CYAN), "Hello world!")
PrintWith(Colorize(SDEFAULT, WHITE), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_BLACK), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_RED), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_GREEN), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_BLUE), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_YELLOW), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_BLUE), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_MAGENTA), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_CYAN), "Hello world!")
PrintWith(Colorize(SDEFAULT, LIGHT_WHITE), "Hello world!")

BLACK_COLOR()

input()
